import Image from "next/image";
import Link from "next/link";
import type { CSSProperties } from "react";
import { Breadcrumb } from "@/components/common/Breadcrumb";
import { Icon } from "@/components/common/Icon";
import { SourceBadge, VersionBadge } from "@/components/common/Badges";
import { SourceBox } from "@/components/common/SourceBox";
import { getBuild, getRelatedUpgrades, getSources } from "@/lib/data/content";
import { JsonLd } from "@/seo/JsonLd";
import { breadcrumbSchema } from "@/seo/schema";
import styles from "@/style/page/content/content.module.css";

const phases = [
  { label: "Early run", title: "Build the runway", icon: "shoe" as const, items: ["Prioritize Jump Height and Luck.", "The cited route keeps roughly two to four ropes.", "Reinforce the small set and delay early fire."] },
  { label: "Mid run", title: "Close the air loop", icon: "rocket" as const, items: ["Add Rocket Fuel behind a strong height base.", "Treat roughly twelve loops as one player's transition signal, not a requirement.", "Confirm a level-up refills the gauge and repeat the cycle twice."] },
  { label: "Late run", title: "Turn safety into score", icon: "fire" as const, items: ["Add rope count and speed after several upgrades fit in one jump.", "Use fire only when losses are sustainable.", "Budget more fuel as later upgrades take longer to reach."] },
];

export default function HighScorePage() {
  const build = getBuild("high-score-build")!;
  const core = getRelatedUpgrades(build.coreUpgrades);
  const sources = getSources(build.sourceIds);
  return (
    <main id="main-content">
      <JsonLd data={breadcrumbSchema([{label:"Home",href:"/"},{label:"High Score Guide",href:"/high-score"}])}/>
      <div className="container"><Breadcrumb items={[{label:"Home",href:"/"},{label:"High Score Guide"}]}/></div>
      <header className={styles.featureHero}>
        <Image src="/images/editorial/high-score-hero.webp" alt="Editorial illustration of Scarlet using Rocket Shoes above a flaming rope during a high-score run" fill priority sizes="100vw"/>
        <div className={styles.heroShade}/><div className={`container ${styles.heroContent}`}><div className={styles.heroBadges}><SourceBadge status="Player Report"/><VersionBadge version="1.0.1"/></div><p className={styles.eyebrow}>SCORE-ATTACK STRATEGY</p><h1>Scarlet Skips High Score Guide</h1><p>Use a published roughly 200,000-point route as a tested framework: height and Luck first, a verified-in-your-run fuel loop second, and rope speed, quantity and fire only after the engine is sustainable.</p><Link href="/run-lab/build-planner?goal=high-score">Plan a score build <Icon name="arrow" size={18}/></Link></div>
      </header>
      <div className={`container ${styles.articleLayout}`}>
        <article className={styles.article}>
          <section className={styles.statStrip}><div><small>COMMUNITY RUN</small><strong>~200,000</strong><span>reported score—not a world record</span></div><div><small>CORE IDEA</small><strong>Air loop</strong><span>height + progress + fuel</span></div><div><small>LATE SCALING</small><strong>Ropes + fire</strong><span>only after stability</span></div></section>
          <section><div className={styles.sectionTitle}><span><Icon name="cards" size={23}/></span><div><p className={styles.kicker}>PICK PRIORITY</p><h2>The high-score core</h2></div></div><div className={styles.miniUpgradeGrid}>{core.map((upgrade,index) => <Link key={upgrade.slug} href={`/upgrades/${upgrade.slug}`} style={{"--card-color":upgrade.color} as CSSProperties}><small>Priority {index + 1}</small><span><Icon name={upgrade.icon} size={27}/></span><strong>{upgrade.shortName}</strong><p>{upgrade.effect}</p></Link>)}</div></section>
          <section><div className={styles.sectionTitle}><span><Icon name="route" size={23}/></span><div><p className={styles.kicker}>BUILD ORDER</p><h2>Three phases, one engine</h2></div></div><div className={styles.phaseCards}>{phases.map((phase,index) => <article key={phase.label}><span className={styles.phaseNumber}>0{index + 1}</span><span className={styles.phaseIcon}><Icon name={phase.icon} size={27}/></span><p className={styles.kicker}>{phase.label}</p><h3>{phase.title}</h3><ul>{phase.items.map((item) => <li key={item}><Icon name="check" size={16}/>{item}</li>)}</ul></article>)}</div></section>
          <section className={styles.explainer}><div><p className={styles.kicker}>PLAYER-REPORTED MECHANIC</p><h2>How the Rocket Fuel loop works</h2><p>A Steam Community guide reports that taking an upgrade refills Rocket Fuel. With enough height and Luck-driven progression, a player may reach another upgrade before the gauge empties, creating repeated powered airtime.</p><p>This interaction is not an official promise of infinite flight. Test the refill in the current run and keep a safe landing until it repeats.</p></div><Image src="/images/official/screenshot-5.jpg" alt="Rocket Shoes active during a Scarlet Skips run" width={640} height={360}/></section>
          <section><div className={styles.sectionTitle}><span><Icon name="gauge" size={23}/></span><div><p className={styles.kicker}>TRANSITION CHECK</p><h2>When the build is ready to scale</h2></div></div><ol className={styles.routeSteps}><li><span>01</span><div><h3>Several loops fit inside one jump</h3><p>The cited player mentions about twelve, but your actual requirement is simply enough loop volume to approach another level-up.</p></div></li><li><span>02</span><div><h3>More than one upgrade can arrive in the air</h3><p>This shows that height and progression are beginning to feed each other instead of relying on every landing.</p></div></li><li><span>03</span><div><h3>Fuel visibly refreshes at level-up</h3><p>Watch the gauge at the selection transition. If it does not refill on your current state, do not plan an infinite loop.</p></div></li><li><span>04</span><div><h3>The bridge repeats</h3><p>Require at least two successful upgrade-to-upgrade cycles before adding ropes, speed or fire that make recovery harder.</p></div></li></ol></section>
          <section><div className={styles.sectionTitle}><span><Icon name="shield" size={23}/></span><div><p className={styles.kicker}>EVIDENCE CHECK</p><h2>How to read the reported numbers</h2></div></div><div className={styles.phaseCards}><article><span className={styles.phaseNumber}>01</span><span className={styles.phaseIcon}><Icon name="trophy" size={27}/></span><p className={styles.kicker}>REPORTED RUN</p><h3>~200,000</h3><p>The guide author reached roughly 200,000 before a crash. It is not an official or verified world record.</p></article><article><span className={styles.phaseNumber}>02</span><span className={styles.phaseIcon}><Icon name="rope" size={27}/></span><p className={styles.kicker}>PERSONAL SIGNAL</p><h3>~12 loops</h3><p>Around twelve loops per jump marked that player&apos;s transition; use engine behavior, not the number, as your test.</p></article><article><span className={styles.phaseNumber}>03</span><span className={styles.phaseIcon}><Icon name="info" size={27}/></span><p className={styles.kicker}>UNCONFIRMED</p><h3>Stat caps</h3><p>The author suspects Luck and rope speed cap, but no value or developer confirmation is available.</p></article></div></section>
          <section><div className={styles.sectionTitle}><span><Icon name="x" size={23}/></span><div><p className={styles.kicker}>FAILURE POINTS</p><h2>Why score runs collapse</h2></div></div><ul className={styles.calloutList}><li><Icon name="x" size={17}/><span><strong>Fire before the engine.</strong> A multiplier cannot rescue a landing window you no longer control.</span></li><li><Icon name="x" size={17}/><span><strong>Too many unreinforced ropes.</strong> Quantity scales maintenance as well as score pressure.</span></li><li><Icon name="x" size={17}/><span><strong>Fuel without progress.</strong> A longer gauge only helps if height and level-ups give that airtime a purpose.</span></li><li><Icon name="x" size={17}/><span><strong>Burning the whole gauge immediately.</strong> Preserve enough margin for a late upgrade or controlled descent until the loop is proven.</span></li><li><Icon name="x" size={17}/><span><strong>Ignoring the rising level cost.</strong> A loop that closes now may fail later as the next upgrade takes more rotations.</span></li><li><Icon name="x" size={17}/><span><strong>Record inflation.</strong> The roughly 200,000 example is one player report, not a verified official leaderboard.</span></li></ul></section>
          <SourceBox sources={sources} version="1.0.1"/>
        </article>
        <aside className={styles.stickyAside}><section><p className={styles.kicker}>QUICK PRIORITY</p><h2>Score build order</h2><ol><li><span>1</span>Jump Height</li><li><span>2</span>Increase Luck</li><li><span>3</span>Rocket Fuel</li><li><span>4</span>Rope pressure</li><li><span>5</span>Ignite late</li></ol><Link href="/builds/high-score-build">Open full build <Icon name="arrow" size={16}/></Link></section><section><p className={styles.kicker}>RUN LAB</p><nav><Link href="/run-lab/upgrade-picker"><Icon name="cards" size={18}/>Compare 3 choices</Link><Link href="/run-lab/records"><Icon name="trophy" size={18}/>Track a score</Link><Link href="/guides/tips"><Icon name="book" size={18}/>Tips &amp; Tricks</Link></nav></section></aside>
      </div>
    </main>
  );
}
