import Link from "next/link";
import { Breadcrumb } from "@/components/common/Breadcrumb";
import { Icon } from "@/components/common/Icon";
import { siteConfig } from "@/config/site";
import styles from "@/style/page/legal/legal.module.css";

type Section = { heading: string; paragraphs: string[]; bullets?: string[] };
type PageData = { title: string; eyebrow: string; intro: string; icon: "info" | "heart" | "shield" | "book"; sections: Section[] };

export const legalPages: Record<string, PageData> = {
  about: { title:"About Scarlet Skips Guide",eyebrow:"INDEPENDENT FAN RESOURCE",intro:"A focused Scarlet Skips knowledge base built to make the difference between game facts, community strategies and unknown data immediately visible.",icon:"heart",sections:[{heading:"Why this site exists",paragraphs:["Scarlet Skips turns one simple input into a run full of branching decisions. Scarlet Skips Guide organizes those decisions around real player goals: learning the rhythm, reaching the ending, climbing for score or testing a strange build."]},{heading:"How information is handled",paragraphs:["Official Steam information is labeled Official. Repeated, visible game behavior may be labeled Community Verified. Individual routes and discoveries remain Player Reports."],bullets:["No invented card names or numeric formulas.","Every strategy page carries a version badge.","Unknown formulas and single-run observations are called out in the article."]},{heading:"Independence",paragraphs:["Scarlet Skips Guide is an independent fan website. It is not developed, sponsored or endorsed by Yerk Games, Valve or Steam."]}] },
  contact: { title:"Contact Scarlet Skips Guide",eyebrow:"CORRECTIONS & FEEDBACK",intro:"Send a source-backed correction, a later official patch, or a reproducible gameplay discovery.",icon:"info",sections:[{heading:"What to include",paragraphs:["Useful reports include the game version, the exact card or route involved, steps to reproduce the observation, and a stable screenshot or video link."],bullets:["Game version and platform.","Clear reproduction steps.","Official announcement, Steam screenshot or video proof."]},{heading:"Email",paragraphs:[`Reach the project at ${siteConfig.email}. Please do not send executable files or personal account information.`]},{heading:"What happens next",paragraphs:["Reports are checked against available primary sources and labeled by evidence strength. A submission does not guarantee publication, and player names are not published without clear permission."]}] },
  privacy: { title:"Privacy Policy",eyebrow:"PLAIN-LANGUAGE POLICY",intro:"Scarlet Skips Guide is designed to work without accounts. The current Build Planner stays in the open page and is not submitted as a public score.",icon:"shield",sections:[{heading:"Build Planner data",paragraphs:["Upgrade picks in the current Build Planner exist only in the active page state. Reloading or closing the page resets that run."],bullets:["No account is required.","The planner does not submit a score.","No public leaderboard is attached to the planner."]},{heading:"Server and hosting data",paragraphs:["The hosting provider may process standard request information such as IP address, browser type, requested URL and timestamps for security, reliability and aggregate traffic measurement. The final deployed provider's own policy also applies."]},{heading:"External links",paragraphs:["Links to Steam, Steam Community, YouTube and Nexus Mods open external services. Their privacy policies and account systems are separate from this website."]},{heading:"Contact",paragraphs:[`Privacy questions can be sent to ${siteConfig.email}.`]}] },
  terms: { title:"Terms of Use",eyebrow:"USE THE GUIDE RESPONSIBLY",intro:"By using Scarlet Skips Guide, you agree to treat its strategies as informational fan guidance rather than guaranteed game outcomes.",icon:"book",sections:[{heading:"Guide accuracy",paragraphs:["Random upgrade choices, future patches and incomplete official documentation can change a run. We aim to cite and version content, but do not guarantee a specific score, ending trigger or result."]},{heading:"Acceptable use",paragraphs:["You may read, link to and use the Build Planner for personal gameplay. Do not disrupt the service, misrepresent the site's content as official Yerk Games material, or republish substantial original site text as your own."]},{heading:"Third-party services",paragraphs:["Steam, Steam Community, YouTube, Nexus Mods and any future hosting or analytics service are governed by their own terms. Links do not imply endorsement."]},{heading:"Changes",paragraphs:["These terms may be updated when site features or hosting arrangements change. The current page is the applicable version."]}] },
  copyright: { title:"Copyright & Fan Content",eyebrow:"OWNERSHIP & ATTRIBUTION",intro:"Scarlet Skips and its official game assets belong to their respective rights holders. This site adds independent guide writing, data organization and planner logic.",icon:"shield",sections:[{heading:"Game ownership",paragraphs:["The official Steam listing identifies the legal copyright as © 2026 YerkDiff and lists Yerk Games as developer and publisher. Scarlet Skips, its name, characters, screenshots and game artwork remain the property of their respective rights holders. Steam is a trademark and service of Valve Corporation."]},{heading:"Site content",paragraphs:["Original guide text, interface design and planner logic on Scarlet Skips Guide are protected by their respective rights. Brief factual references and official screenshots are used for identification, commentary and fan-guide purposes."],bullets:["Official images are not offered as standalone downloads.","Third-party mod files and images are not copied.","No affiliation or endorsement is claimed."]},{heading:"Rights-holder requests",paragraphs:[`For an attribution correction or rights-holder request, contact ${siteConfig.email} with the URL and a clear description of the material.`]}] },
};

export default function LegalPage({ slug }: { slug: string }) {
  const page = legalPages[slug];
  return <main id="main-content"><div className="container"><Breadcrumb items={[{label:"Home",href:"/"},{label:page.title}]}/></div><header className={`container ${styles.hero}`}><span><Icon name={page.icon} size={34}/></span><div><p>{page.eyebrow}</p><h1>{page.title}</h1><p>{page.intro}</p></div></header><div className={`container ${styles.layout}`}><article>{page.sections.map((section) => <section key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets && <ul>{section.bullets.map((bullet) => <li key={bullet}><Icon name="check" size={17}/>{bullet}</li>)}</ul>}</section>)}</article><aside><Icon name="info" size={25}/><h2>Independent guide</h2><p>This site is not affiliated with Yerk Games or Valve. Gameplay claims on strategy pages are sourced and versioned.</p><Link href="/about">Read our sourcing policy</Link></aside></div></main>;
}
