import Link from "next/link";
import { Breadcrumb } from "@/components/common/Breadcrumb";
import { Icon } from "@/components/common/Icon";
import { updates } from "@/lib/data/content";
import styles from "@/style/page/content/content.module.css";

export default function UpdatesPage() {
  return <main id="main-content"><div className="container"><Breadcrumb items={[{label:"Home",href:"/"},{label:"Updates"}]}/></div><header className={`container ${styles.simpleHero}`}><span><Icon name="spark" size={34}/></span><div><p className={styles.eyebrow}>WHAT CHANGED IN THE GAME?</p><h1>Scarlet Skips updates</h1><p>Read the patch in plain English, then see which builds or tricks are worth testing again.</p></div></header><div className={`container ${styles.updateLayout}`}><section className={styles.timeline} aria-labelledby="update-history"><h2 id="update-history" className="sr-only">Update history</h2>{updates.map((entry) => <article key={entry.slug}><div className={styles.timelineRail}><span/><i/></div><div className={styles.updateCard}><div className={styles.updateMeta}><span>v{entry.version}</span><time>{entry.date}</time></div><h2>{entry.title}</h2><p>{entry.summary}</p><ul>{entry.changes.slice(0,3).map((change) => <li key={change}><Icon name="check" size={16}/>{change}</li>)}</ul><Link href={`/updates/${entry.slug}`}>What does this change for my run? <Icon name="arrow" size={17}/></Link></div></article>)}</section><aside className={styles.updateAside}><section><Icon name="shield" size={27}/><h2>Why the version matters</h2><p>Rocket Shoes and extinguished ropes have already been fixed once. Older advice may not behave the same way now.</p></section><section><Icon name="info" size={27}/><h2>Found a newer patch?</h2><p>Send us the official announcement and we will re-check the affected guides.</p><Link href="/contact">Contact the site</Link></section></aside></div></main>;
}
